# Generated by Django 6.1.1 on 2026-09-18 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='Email address to notify.', max_length=254)),
                ('notified', models.BooleanField(default=False, help_text='Set to True once the notification email has been sent.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='api.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Leave blank to alert on any variant restocking.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='api.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('email', 'variant', 'notified')},
            },
        ),
    ]
