# Generated by Django 6.1.1 on 2026-09-18 10:20

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stockalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge', models.CharField(help_text="Small pill label, e.g. 'New Arrivals'.", max_length=60)),
                ('headline', models.CharField(help_text='Large bold heading shown on the slide.', max_length=120)),
                ('sub', models.CharField(blank=True, help_text='Short supporting sentence beneath the headline.', max_length=200)),
                ('cta_label', models.CharField(default='Shop Now', help_text="Button label, e.g. 'Shop Now'.", max_length=40)),
                ('cta_href', models.CharField(default='/shop', help_text='URL the button links to (relative or absolute).', max_length=200)),
                ('bg_image', models.ImageField(blank=True, help_text='Background image for the slide. Leave blank for a plain colour.', null=True, upload_to=api.models.hero_slide_image_path)),
                ('accent_color', models.CharField(default='#2563eb', help_text='Hex colour for the badge and CTA button, e.g. #2563eb.', max_length=7)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the carousel.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active slides are shown on the home page.')),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
