# Generated by Django 6.1.1 on 2026-09-23 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_heroslide'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='assignment_status',
            field=models.CharField(default='unassigned', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location_captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location_source',
            field=models.CharField(blank=True, choices=[('current_location', 'Current location'), ('manual', 'Manual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('packed', 'Packed'), ('assigned', 'Delivery Boy Assigned'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(max_length=40, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('cnic_number', models.CharField(max_length=30, unique=True)),
                ('cnic_front', models.FileField(blank=True, upload_to='delivery/cnic/')),
                ('cnic_back', models.FileField(blank=True, upload_to='delivery/cnic/')),
                ('profile_photo', models.ImageField(blank=True, upload_to='delivery/profiles/')),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('complete_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('permanent_address', models.CharField(blank=True, max_length=255)),
                ('current_address', models.CharField(blank=True, max_length=255)),
                ('vehicle_type', models.CharField(blank=True, choices=[('motorcycle', 'Motorcycle'), ('bicycle', 'Bicycle'), ('car', 'Car'), ('other', 'Other')], max_length=20)),
                ('vehicle_registration_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=100)),
                ('vehicle_color', models.CharField(blank=True, max_length=50)),
                ('vehicle_registration_document', models.FileField(blank=True, upload_to='delivery/vehicles/')),
                ('driving_license_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('driving_license', models.FileField(blank=True, upload_to='delivery/licenses/')),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_boys', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_delivery_boys', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_boy_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_delivery_boys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='api.deliveryboy'),
        ),
        migrations.CreateModel(
            name='DeliveryBoyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('delivery_boy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='api.deliveryboy')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('unassigned', 'Unassigned')], default='active', max_length=12)),
                ('distance_at_assignment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='api.deliveryboy')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignments', to='api.order')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deliveryboy',
            index=models.Index(fields=['employment_status', 'verification_status'], name='api_deliver_employm_8c492e_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryboy',
            index=models.Index(fields=['city'], name='api_deliver_city_b2d900_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryboylocation',
            index=models.Index(fields=['is_online', 'last_seen_at'], name='api_deliver_is_onli_7e93c7_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdeliveryassignment',
            index=models.Index(fields=['order', 'status'], name='api_orderde_order_i_1f6ecf_idx'),
        ),
    ]
