# Generated by Django 6.1.1 on 2026-09-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_assigned_at_order_assigned_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='driving_license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='vehicle_registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
